// Where each SetupCommand that appends --json is proven to print a document crew can parse: a
// Go-written golden (crew's tests write it from the function the command prints), or the live spec
// (test/live/setup-reads.test.ts runs it against a real crew and fails when its stdout does not
// parse). null: the variant runs without --json. commands.spec checks this against the traits.
import type { SetupCommandType } from '../../src/crew/commands.js';

export type JsonEvidence = { golden: string } | 'live' | null;

export const JSON_EVIDENCE: Record<SetupCommandType, JsonEvidence> = {
	ls_projects: { golden: 'ls-projects.json' },
	ls_workspaces: { golden: 'ls-workspaces.json' },
	ls_worktrees: { golden: 'ls-worktrees.json' },
	ls_bindings: { golden: 'ls-bindings.json' },
	ls_bindings_preview: { golden: 'ls-bindings-preview.json' },
	ls_overrides: { golden: 'ls-overrides.json' },
	ls_bases: { golden: 'ls-bases.json' },
	show: { golden: 'show-worktree.json' },
	scan_checkouts: { golden: 'scan-checkouts.json' },
	setup_status: { golden: 'setup-status-ok.json' },
	setup_logs: { golden: 'setup-logs.json' },
	check_status: { golden: 'check-status-passed.json' },
	dev_status: { golden: 'dev-status.json' },
	dev_check: { golden: 'dev-check.json' },
	dev_logs: { golden: 'dev-logs.json' },
	env: { golden: 'env.json' },
	fix: null,
	import_plan: { golden: 'import-plan.json' },
	export: null,
	clean_dry_run: { golden: 'clean-dry-run.json' },
	trash: { golden: 'trash.json' },
	config_show: { golden: 'config-show.json' },
	proxy_status: { golden: 'proxy-status.json' },
	update_check: { golden: 'update-check.json' },
	server_status: { golden: 'server-status.json' },
	machines_ls: { golden: 'server-machines.json' },
	keys_status: { golden: 'server-keys.json' },
	discord_status: { golden: 'server-discord-status.json' },
	debug_tail: null,
	doctor: 'live',
	migrate_dry_run: { golden: 'migrate-dry-run.json' },
	rm_workspace_project_dry_run: { golden: 'rm-workspace-project-dry-run.json' },
	rm_worktree_dry_run: { golden: 'rm-worktree-dry-run.json' },
	add_binding_dry_run: { golden: 'add-binding-dry-run.json' },
	add_binding_scan: { golden: 'add-binding-scan.json' },
	add_project: null,
	update_project: null,
	rm_project: null,
	dev_add: null,
	dev_rm: null,
	add_binding: null,
	add_binding_scan_apply: { golden: 'add-binding-scan-apply.json' },
	rm_binding: null,
	check_project: 'live',
	add_workspace: 'live',
	rm_workspace_project: null,
	rm_workspace: null,
	add_worktree: 'live',
	rm_worktree: null,
	rename_worktree: 'live',
	duplicate_worktree: 'live',
	add_override: null,
	rm_override: null,
	setup_rerun: 'live',
	verify: 'live',
	dev_start: 'live',
	dev_stop: null,
	dev_restart: 'live',
	import_project: 'live',
	import_workspace: 'live',
	import_all: 'live',
	clean: 'live',
	trash_empty: { golden: 'trash-empty.json' },
	config_set: null,
	config_refresh: null,
	proxy_trust: 'live',
	migrate: { golden: 'migrate.json' },
	// Replaces the binary: never run live.
	update: { golden: 'update.json' },
	server_restart: null,
	server_stop: null,
	uninstall: null,
	machines_add: 'live',
	machines_rm: 'live',
	machines_rename: 'live',
	// Checks the key with its provider: never run live.
	keys_set: { golden: 'server-keys-set.json' },
	discord_off: 'live',
};

export const LIVE_JSON_TYPES = (Object.keys(JSON_EVIDENCE) as SetupCommandType[]).filter(
	(type) => JSON_EVIDENCE[type] === 'live',
);
