# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crew < Formula
  desc "Agent team launcher, workspace manager & package registry"
  homepage "https://github.com/FurlanLuka/homebrew-tap"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FurlanLuka/homebrew-tap/releases/download/v1.2.1/crew_1.2.1_darwin_amd64.tar.gz"
      sha256 "127c70e7b7a70be5ec16a1b759086ecd696832693541cb14f2bcb14371337804"

      define_method(:install) do
        bin.install "crew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FurlanLuka/homebrew-tap/releases/download/v1.2.1/crew_1.2.1_darwin_arm64.tar.gz"
      sha256 "1896c19490a1235ff497e583bbd2678917d88e0c52e3ce390ea3905bfdd64503"

      define_method(:install) do
        bin.install "crew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FurlanLuka/homebrew-tap/releases/download/v1.2.1/crew_1.2.1_linux_amd64.tar.gz"
      sha256 "96d32ee26cebe2e0cee34137e26441961ac0c413e5d3527102767b7c5f02dfe9"
      define_method(:install) do
        bin.install "crew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FurlanLuka/homebrew-tap/releases/download/v1.2.1/crew_1.2.1_linux_arm64.tar.gz"
      sha256 "c5fbb26abab7d7a384b3dd09f92aa905f474e35245394ebb969a3536544777d2"
      define_method(:install) do
        bin.install "crew"
      end
    end
  end

  test do
    assert_match "crew", shell_output("#{bin}/crew --version")
  end
end
